[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/next"

[functions]
  included_files = [
    "public/**",
    "data/**",
    "config/**",
    "lib/**",
    "content/**"
  ]